version: "3"

services:
  vue_project:
    build: vue-project
    logging: 
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    ports:
      - "5173:80"
  asp_project:
    build: asp-project
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    ports:
      - "7227:80"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=7h4I4n@06#c0
      - MYSQL_USER=progneo
      - MYSQL_PASSWORD=f%9#LUObh19K
      - MYSQL_DATABASE=anime
      - MYSQL_HOST=0.0.0.0
      - MYSQL_PORT=3306
    volumes:
      - ./.mysql-data/db:/var/lib/mysql
